branches:
  only:
    - devel
    - devel-fe
    - devel-be

matrix:
  include:
    - language: python
      python: "3.5"
      before_script:
        - pip install -r requirements.txt
      script:
        - ./test.sh
    - language: node_js
      node_js: "lts/*"
      before_script:
        - npm install
      script:
        - ./test.sh

notifications:
  slack: swpp2018s:eXObOVtbqFO42dFDWrUr23gh
