sudo: required
dist: trusty
branches:
  only:
    - devel
    - devel-fe
    - devel-be
language: python
python: "3.5"
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
node_js: "lts/*"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install -r requirements.txt
  - npm install
  - chmod +x ./test.sh
script:
  - ./test.sh

notifications:
  slack: swpp2018s:eXObOVtbqFO42dFDWrUr23gh
