sudo: required
dist: trusty
branches:
  only:
    - devel
    - devel-fe
    - devel-be
  except:
    - /^fe-.*$/
    - /^be-.*$/

language: python
python:
  - 3.5
node_js: "9.10.1"
addons:
  chrome: stable
env:
  - PYTHONPATH=. COVERALLS_SERVICE_NAME=travis-pro

before_script:
  - pip install -r requirements.txt
  - pip install pyyaml # for coveralls
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=qBBVD53FS9tIsJy4i6GcMCZKcUY7ZO4dG
  - npm install
  - chmod +x ./test.sh
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script:
  - ./test.sh
after_script:
  - if [ "$TRAVIS_BRANCH" = "devel-fe" ]; then npm run coveralls; fi

notifications:
  slack: swpp2018s:eXObOVtbqFO42dFDWrUr23gh
