sudo: required
dist: trusty
branches:
  only:
    - devel
    - devel-fe
    - devel-be
  except:
    - /^fe-.*$/
    - /^be-.*$/

language: java
jdk:
  - oraclejdk8
node_js: "9.10.1"
addons:
  chrome: stable

before_script:
  - sudo add-apt-repository ppa:fkrull/deadsnakes
  - sudo apt-get update
  - sudo apt-get install python3.5
  - sudo apt-get install python3-pip
  - sudo pip3 install --upgrade pip
  - sudo pip3 install -r requirements.txt
  - npm install
  - chmod +x ./test.sh
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script:
  - ./test.sh

notifications:
  slack: swpp2018s:eXObOVtbqFO42dFDWrUr23gh
