branches:
  only:
    - devel
    - devel-fe
    - devel-be

matrix:
  include:
    - language: python
      python: "3.5"
      before_script:
        - pip install -r requirements.txt
      script:
        - if [ "$TRAVIS_BRANCH" = "devel_be" ]; then python manage.py test
    - language: node_js
      node_js: "lts/*"
      before_script:
        - npm install
      script:
        - if [ "$TRAVIS_BRANCH" = "devel_fe" ]; then npm test_fe
        - if [ "$TRAVIS_BRANCH" = "devel" ]; then npm test

notifications:
  slack: swpp2018s:eXObOVtbqFO42dFDWrUr23gh
