// navbar
export const NAVBAR_CHANGE_PAGE = 'navbar/NAVBAR_CHANGE_PAGE'
export const NAVBAR_SET_BACKGROUND = 'navbar/NAVBAR_SET_BACKGROUND'
export const NAVBAR_UNSET_BACKGROUND = 'navbar/NAVBAR_UNSET_BACKGROUND'
export const NAVBAR_TOGGLE_BURGER = 'navbar/NAVBAR_TOGGLE_BURGER'
export const NAVBAR_CLOSE_BURGER = 'navbar/NAVBAR_CLOSE_BURGER'
export const NAVBAR_UPDATE_SCROLL = 'navbar/NAVBAR_UPDATE_SCROLL'

// closet
export const CLOSET_CHANGE_MENU = 'closet/CLOSET_CHANGE_MENU'
