# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-28 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='media/default_image.jpeg', upload_to='')),
                ('is_wildcard', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MxM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('is_on_recommendation', models.BooleanField(default=False)),
                ('is_on_evaluation', models.BooleanField(default=False)),
                ('clothes', models.ManyToManyField(to='app.Clothes')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mxms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('stars', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('mxm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.MxM')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('reply_content', models.CharField(default='', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('mxm', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.MxM')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('Color', 'Color'), ('Season', 'Season'), ('Texture', 'Texture'), ('Category', 'Category')], default='Color', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='tag',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
