# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-17 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', 'db_initial'),
        ('app', 'tag_initial'),
    ]

    operations = [
    ]
