# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-16 02:34
from __future__ import unicode_literals
from django.db import migrations, models

def tag_initialize(apps, schema_editor):
    Tag = apps.get_model("app", "Tag")

    with open('app/tags.txt', 'r') as tag_file:
        id = 0
        type = ''
        content = ''
        for line in tag_file:
            line = line[:-1]
            if line in ['Color', 'Season', 'Texture', 'Category']:
                type=line
            else:
                content=line
                Tag(id = id, type = type, content = content).save()
                id = id + 1


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(tag_initialize),
    ]
